# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPageTest(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".header-today").click()
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("bra16033@byui.edu")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").click()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password").send_keys("sergio@2025")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
  def test_directoryPageTest(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-grid").click()
    self.driver.find_element(By.ID, "directory-list").click()
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9)").click()
  
  def test_homePageTest(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1151, 951)
    self.driver.find_element(By.CSS_SELECTOR, "#nopad > h2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home-main").click()
    self.driver.find_element(By.CSS_SELECTOR, "#nopad > h2").click()
    self.driver.find_element(By.ID, "nopad").click()
    self.driver.find_element(By.CSS_SELECTOR, "#nopad > h2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home-main").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").text == "Teton Elementary"
    self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").text == "Teton Post Office"
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Sergio")
    self.driver.find_element(By.NAME, "lname").send_keys("Bravo")
    self.driver.find_element(By.NAME, "bizname").send_keys("Mucacran")
    self.driver.find_element(By.NAME, "biztitle").send_keys("Gerente")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("sergio@mucacran.com")
    self.driver.find_element(By.NAME, "cellphone").click()
    self.driver.find_element(By.NAME, "cellphone").send_keys("+593980837662")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".myradio:nth-child(15)").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("www.mucacran.com")
    self.driver.find_element(By.CSS_SELECTOR, "textarea").send_keys("mi empresa")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("https://www.mucacran.com")
    self.driver.find_element(By.NAME, "submit").click()
  
  def test_joinPageTest(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Sergio")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("Bravo")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").click()
    element = self.driver.find_element(By.NAME, "bizname")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("Mucacran")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").click()
    element = self.driver.find_element(By.NAME, "biztitle")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "biztitle").send_keys("Gerente")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("sergio@mucacran.com")
    self.driver.find_element(By.NAME, "cellphone").send_keys("+593980837662")
    self.driver.find_element(By.CSS_SELECTOR, "fieldset").click()
    self.driver.find_element(By.NAME, "submit").click()
  
